var firstLoad = true;var buttonColours = ["red", "blue", "green", "yellow"];var gamePattern = [];var userClickedPattern = [];var level = 0;var started = false;var score = 0;var highScore = 0;var viewSize = $(document).width();
$(".btn").click(function(){var userChosenColour=$(this).attr("id");userClickedPattern.push(userChosenColour);playSound(userChosenColour);animatePress(userChosenColour);checkAnswer(userClickedPattern.length-1)});
function nextSequence(){userClickedPattern=[];level++;$("#level-title").text("Level "+level);var randomNumber=Math.floor(Math.random()*4);var randomChosenColour=buttonColours[randomNumber];gamePattern.push(randomChosenColour);$("#"+randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);playSound(randomChosenColour)}
function animatePress(currentColour) {$("#" + currentColour).addClass("pressed");setTimeout(function() {$("#" + currentColour).removeClass("pressed");},100);}
function playSound(name) {var audio = new Audio("sounds/" + name + ".mp3");audio.play();}
function startOver() {level = 0;gamePattern = [];started = false;}
if (viewSize <= 1120) {if(firstLoad){$("h1").text("Press Start button to play");firstLoad=false;} $(".start-btn").click(() => {if (!started) {$("#level-title").text("Level " + level);nextSequence();started = true;$(".score-box").animate({height: 1,opacity: 0});$(".btn").animate({opacity: "100%"});}}); $(".start-btn").click(() => {$(".start-btn").animate({width: 44,height:44},50).animate({width: 52, height: 52});});
function checkAnswer(currentLevel) {if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {if (userClickedPattern.length === gamePattern.length) {setTimeout(function() {nextSequence();},1000);}} else {playSound("wrong");score = level;if (score > highScore) {highScore = score;}$("body").addClass("game-over");$(".score-box").animate({opacity: "80%",border: "10%",height: 180}, 500);$("#p1").text("Score : " + score);$("#p2").text("High Score : " + highScore);$("#level-title").text("Game Over, Press start to Play again");$(".btn").animate({opacity: "20%"});setTimeout(() => {$("body").removeClass("game-over");}, 300);startOver();}}}
else {$(document).keypress(() => {if (!started) {$("#level-title").text("Level " + level);nextSequence();started = true;$(".score-box").animate({opacity: 0});$(".btn").animate({opacity: "100%"});}});
function checkAnswer(currentLevel) {if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {if (userClickedPattern.length === gamePattern.length) {setTimeout(function() {nextSequence();}, 1000);}} else {playSound("wrong");score = level;if(score>highScore){ highScore = score;}
$("body").addClass("game-over");$(".score-box").animate({opacity: "80%",border: "10%",height: 320},500);$("#p1").text("Score : " + score );$("#p2").text("\n High Score : " + highScore);$("#level-title").text("Game Over, Press Any Key to Restart");$(".btn").animate({opacity:"20%"});setTimeout(() => {$("body").removeClass("game-over");}, 300);startOver();}}}
